# TASK-01 — Data Preprocessing of Student Dataset

**Objective:** Perform end-to-end data preprocessing on the Student Dataset using Python and Pandas.  
This includes loading and exploring the dataset, identifying and handling missing values, encoding categorical variables, and splitting the data for machine learning model training.

## Step 1: Import Required Libraries

Before we begin, we need to import all the necessary Python libraries.  
- pandas is used for data loading and manipulation  
- sklearn is used for label encoding and train-test splitting

In [1]:
# Importing pandas for data handling
import pandas as pd

# Importing LabelEncoder for encoding the Gender column
from sklearn.preprocessing import LabelEncoder

# Importing train_test_split for splitting the dataset
from sklearn.model_selection import train_test_split

## Step 2: Load the Dataset

We load the student dataset using pandas.read_csv().  
Make sure the dataset CSV file is uploaded to your Colab session before running this cell.

In [2]:
# Loading the CSV file into a pandas DataFrame
df = pd.read_csv('student_data_100_preprocess.csv')

# Quick confirmation that the file loaded without errors
print("Dataset loaded successfully!")

Dataset loaded successfully!

## Step 3: Explore the Dataset

Before doing any preprocessing, it is important to understand the structure and content of the dataset.  
We will look at the first and last few rows, check the shape, column names, data types, and get a statistical summary.

In [3]:
# Displaying the first 5 rows of the dataset
print("First 5 rows of the dataset:")
df.head()

First 5 rows of the dataset:

   Gender   Age  Hours_Studied  Attendance Parental_Education  Final_Score
0    Male   NaN            1.0        65.0           Graduate         95.0
1  Female  21.0            1.0        80.0           Graduate         70.0
2    Male   NaN            3.0        60.0       Postgraduate         60.0
3    Male  21.0            2.0        60.0        High School         80.0
4    Male  20.0            5.0        80.0           Graduate          NaN

In [4]:
# Displaying the last 5 rows of the dataset
print("Last 5 rows of the dataset:")
df.tail()

Last 5 rows of the dataset:

    Gender   Age  Hours_Studied  Attendance Parental_Education  Final_Score
95  Female  18.0            6.0         NaN       Postgraduate         65.0
96  Female  20.0            6.0        95.0        High School          NaN
97  Female  20.0            3.0        80.0                NaN         75.0
98  Female  18.0            6.0        60.0                NaN         50.0
99    Male  19.0            8.0        90.0                NaN         90.0

In [5]:
# Printing the shape of the dataset (rows, columns)
print("Shape of the dataset:", df.shape)

Shape of the dataset: (100, 6)

In [6]:
# Printing all column names in the dataset
print("Column names:", df.columns.tolist())

Column names: ['Gender', 'Age', 'Hours_Studied', 'Attendance', 'Parental_Education', 'Final_Score']

In [7]:
# Checking the data type of each column
print("Data types of each column:")
print(df.dtypes)

Data types of each column:
Gender                 object
Age                   float64
Hours_Studied         float64
Attendance            float64
Parental_Education     object
Final_Score           float64
dtype: object

### 3.1 Identifying Numerical and Categorical Columns

We need to separate numerical and categorical columns because they require different preprocessing techniques.  
- Numerical columns will be handled using mean imputation  
- Categorical columns will be handled using mode imputation and encoding

In [8]:
# Identifying numerical columns (columns with integer or float values)
numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
print("Numerical columns:", numerical_cols)

Numerical columns: ['Age', 'Hours_Studied', 'Attendance', 'Final_Score']

In [9]:
# Identifying categorical columns (columns with object/string values)
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print("Categorical columns:", categorical_cols)

Categorical columns: ['Gender', 'Parental_Education']

### 3.2 Statistical Summary of Numerical Columns

The describe() function gives us a statistical overview of numerical columns including count, mean, standard deviation, min, max, and quartile values.  
This helps us understand the distribution and range of values in each column.

In [10]:
# Statistical summary of all numerical columns
print("Statistical summary of numerical columns:")
df.describe()

Statistical summary of numerical columns:

             Age  Hours_Studied  Attendance  Final_Score
count  91.000000      90.000000   92.000000    93.000000
mean   19.417582       4.366667   76.684783    74.247312
std     1.174412       2.348559   11.843234    14.632198
min    18.000000       1.000000   60.000000    50.000000
25%    18.000000       3.000000   65.000000    60.000000
50%    19.000000       4.000000   77.500000    75.000000
75%    21.000000       6.000000   85.000000    90.000000
max    21.000000       8.000000   95.000000    95.000000

## Step 4: Identify Missing Values

Real-world datasets usually have missing values. We need to find out which columns have missing data and how many values are missing in each column.  
We use isnull().sum() to count the number of missing values per column.

In [11]:
# Counting missing values in each column
print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
Gender                 0
Age                    9
Hours_Studied         10
Attendance             8
Parental_Education    13
Final_Score            7
dtype: int64

In [12]:
# Getting the total count of missing values in the entire dataset
total_missing = df.isnull().sum().sum()
print("Total missing values in the dataset:", total_missing)

Total missing values in the dataset: 47

Observations:  
From the output above, we can see that the following columns contain missing values:
- Age — numerical column → will use mean to fill
- Hours_Studied — numerical column → will use mean to fill
- Attendance — numerical column → will use mean to fill
- Final_Score — numerical column → will use mean to fill
- Parental_Education — categorical column → will use mode to fill

The Gender column has no missing values in this dataset, but we will verify this during the verification step.

## Step 5: Handle Missing Values using fillna()

We will now fill the missing values using the appropriate strategy for each column type:
- Mean filling for numerical columns: Age, Hours_Studied, Attendance, Final_Score
- Mode filling for categorical columns: Parental_Education

Using mean for numerical columns ensures we don't bias the distribution, while mode (most frequent value) is the safest choice for categorical columns.

In [13]:
# Filling missing values in the 'Age' column with its mean value
age_mean = df['Age'].mean()
print("Mean value of Age:", round(age_mean, 2))
df['Age'] = df['Age'].fillna(age_mean)

Mean value of Age: 19.42

In [14]:
# Filling missing values in the 'Hours_Studied' column with its mean value
hours_mean = df['Hours_Studied'].mean()
print("Mean value of Hours_Studied:", round(hours_mean, 2))
df['Hours_Studied'] = df['Hours_Studied'].fillna(hours_mean)

Mean value of Hours_Studied: 4.37

In [15]:
# Filling missing values in the 'Attendance' column with its mean value
attendance_mean = df['Attendance'].mean()
print("Mean value of Attendance:", round(attendance_mean, 2))
df['Attendance'] = df['Attendance'].fillna(attendance_mean)

Mean value of Attendance: 76.68

In [16]:
# Filling missing values in the 'Final_Score' column with its mean value
score_mean = df['Final_Score'].mean()
print("Mean value of Final_Score:", round(score_mean, 2))
df['Final_Score'] = df['Final_Score'].fillna(score_mean)

Mean value of Final_Score: 74.25

In [17]:
# Filling missing values in the 'Parental_Education' column with its mode (most frequent value)
parental_mode = df['Parental_Education'].mode()[0]
print("Mode value of Parental_Education:", parental_mode)
df['Parental_Education'] = df['Parental_Education'].fillna(parental_mode)

Mode value of Parental_Education: Graduate

### 5.1 Verify — No Missing Values Remain

After filling all missing values, we run the missing value check again to confirm that there are no remaining nulls in the dataset.

In [18]:
# Verifying that no missing values remain
print("Missing values after filling:")
print(df.isnull().sum())

Missing values after filling:
Gender                0
Age                   0
Hours_Studied         0
Attendance            0
Parental_Education    0
Final_Score           0
dtype: int64

In [19]:
# Re-running info() to confirm the changes made to the dataset
print("Dataset info after handling missing values:")
df.info()

Dataset info after handling missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Gender              100 non-null    object
 1   Age                 100 non-null    float64
 2   Hours_Studied       100 non-null    float64
 3   Attendance          100 non-null    float64
 4   Parental_Education  100 non-null    object
 5   Final_Score         100 non-null    float64
dtypes: float64(4), object(2)
memory usage: 4.8+ KB

In [20]:
# Re-running describe() to see updated statistics after filling missing values
print("Statistical summary after handling missing values:")
df.describe()

Statistical summary after handling missing values:

              Age  Hours_Studied  Attendance  Final_Score
count  100.000000     100.000000  100.000000   100.000000
mean    19.417582       4.366667   76.684783    74.247312
std      1.119758       2.226788   11.354641    14.105415
min     18.000000       1.000000   60.000000    50.000000
25%     18.000000       3.000000   65.000000    65.000000
50%     19.000000       4.000000   76.684783    75.000000
75%     20.250000       6.000000   85.000000    85.000000
max     21.000000       8.000000   95.000000    95.000000

## Step 6: Encode Categorical Variables

Machine learning models work only with numerical data. So we need to convert categorical columns to numeric format.  
We will use two different encoding techniques as specified:
- Label Encoding for Gender — since it has only two unique values (Male/Female), label encoding is appropriate
- One-Hot Encoding for Parental_Education — since it has more than two categories, one-hot encoding avoids any unintended ordinal relationship

In [21]:
# Applying Label Encoding to the 'Gender' column
# Male -> 1, Female -> 0 (or based on alphabetical order)
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

# Confirming the encoding
print("Gender column after Label Encoding:")
print(df['Gender'].value_counts())

Gender column after Label Encoding:
Gender
0    56
1    44
Name: count, dtype: int64

In [22]:
# Applying One-Hot Encoding to the 'Parental_Education' column using pandas get_dummies()
# This creates a new binary column for each unique category
df = pd.get_dummies(df, columns=['Parental_Education'])

# Displaying the new columns created by one-hot encoding
print("Columns after One-Hot Encoding of Parental_Education:")
print(df.columns.tolist())

Columns after One-Hot Encoding of Parental_Education:
['Gender', 'Age', 'Hours_Studied', 'Attendance', 'Final_Score', 'Parental_Education_Graduate', 'Parental_Education_High School', 'Parental_Education_Postgraduate']

### 6.1 Confirm Dataset Contains Only Numerical Values

After encoding, the dataset should have no more categorical (object type) columns.  
We use info() to verify this.

In [23]:
# Verifying that all columns are now numeric — no object dtype columns should remain
print("Dataset info after encoding:")
df.info()

Dataset info after encoding:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Gender                           100 non-null    int64
 1   Age                              100 non-null    float64
 2   Hours_Studied                    100 non-null    float64
 3   Attendance                       100 non-null    float64
 4   Final_Score                      100 non-null    float64
 5   Parental_Education_Graduate      100 non-null    bool
 6   Parental_Education_High School   100 non-null    bool
 7   Parental_Education_Postgraduate  100 non-null    bool
dtypes: bool(3), float64(4), int64(1)
memory usage: 4.3 KB

In [24]:
# Displaying the first few rows of the fully encoded dataset
print("First 5 rows of the encoded dataset:")
df.head()

First 5 rows of the encoded dataset:

,Gender,Age,Hours_Studied,Attendance,Final_Score,Parental_Education_Graduate,Parental_Education_High School,Parental_Education_Postgraduate
0,1,19.417582,1.0,65.0,95.000000,True,False,False
1,0,21.000000,1.0,80.0,70.000000,True,False,False
2,1,19.417582,3.0,60.0,60.000000,False,False,True
3,1,21.000000,2.0,60.0,80.000000,False,True,False
4,1,20.000000,5.0,80.0,74.247312,True,False,False

## Step 7: Prepare Data for Model Training

The dataset is now clean and fully numerical. The final step before model training is to:
1. Separate the features (X) and the target variable (y)
2. Split the data into training set (80%) and testing set (20%)

We use train_test_split() from scikit-learn with a fixed random_state to ensure reproducible results.

In [25]:
# Separating features (X) and target variable (y)
# Target column is 'Final_Score' as specified in the task
X = df.drop(columns=['Final_Score'])   # All columns except Final_Score are features
y = df['Final_Score']                  # Final_Score is the target we want to predict

print("Shape of features (X):", X.shape)
print("Shape of target (y):", y.shape)

Shape of features (X): (100, 7)
Shape of target (y): (100,)

In [26]:
# Splitting the dataset into training (80%) and testing (20%) sets
# random_state=42 is used for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Confirming the split sizes
print("Training set size (X_train):", X_train.shape)
print("Testing set size  (X_test): ", X_test.shape)
print("Training labels   (y_train):", y_train.shape)
print("Testing labels    (y_test): ", y_test.shape)

Training set size (X_train): (80, 7)
Testing set size  (X_test):  (20, 7)
Training labels   (y_train): (80,)
Testing labels    (y_test):  (20,)

## Summary

The following preprocessing steps were completed successfully:

1. Dataset Loaded — The student dataset was loaded using Pandas and explored in detail
2. Exploration Done — Shape, column names, data types, numerical/categorical columns, and statistical summary were all reviewed
3. Missing Values Identified — Used isnull().sum() to find missing data across columns
4. Missing Values Handled — Mean used for numerical columns; mode used for Parental_Education
5. Categorical Encoding Applied — Label Encoding for Gender; One-Hot Encoding for Parental_Education
6. Data Split — Dataset split into 80% training and 20% testing with random_state=42

The dataset is now fully preprocessed and ready for machine learning model training.